/*
 * Copyright (c) 2025 - 2026, Nordic Semiconductor ASA
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef NRFX_CRACEN_H
#define NRFX_CRACEN_H

#include <nrfx.h>
#include <hal/nrf_cracen.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @defgroup nrfx_cracen CRACEN driver
 * @{
 * @ingroup nrf_cracen
 * @brief   Cryptographic accelerator engine (CRACEN) peripheral driver
 */

/**
 * @brief Function for initializing the CRACEN driver and peripheral.
 *
 * @note This initialization is relatively slow and power consuming.
 *
 * @note This function assumes exclusive access to the CRACEN TRNG and CryptoMaster, and may
 *       not be used while any other component is using those peripherals.
 *
 * @retval 0          Initialization was successful.
 * @retval -ECANCELED Unexpected error.
 * @retval -EALREADY  Driver was already initialized.
 */
int nrfx_cracen_init(void);

/**
 * @brief Function for uninitializing the CRACEN driver.
 */
void nrfx_cracen_uninit(void);

#if NRF_CRACEN_HAS_CRYPTOMASTER
/**
 * @brief Function for initializing the CRACEN CTR_DRBG random generator.
 *
 * @deprecated Use @ref nrfx_cracen_init instead.
 *
 * @note This initialization is relatively slow and power consuming.
 *
 * @note This function assumes exclusive access to the CRACEN TRNG and CryptoMaster, and may
 *       not be used while any other component is using those peripherals.
 *
 * @retval 0          Initialization was successful.
 * @retval -ECANCELED Unexpected error.
 * @retval -EALREADY  Driver was already initialized.
 */
NRFX_STATIC_INLINE int nrfx_cracen_ctr_drbg_init(void);

/**
 * @brief Function for uninitializing the CRACEN CTR_DRBG random generator.
 *
 * @deprecated Use @ref nrfx_cracen_uninit instead.
 */
NRFX_STATIC_INLINE void nrfx_cracen_ctr_drbg_uninit(void);

/**
 * @brief Function for filling the specified @p p_buf buffer with @p size bytes of random data
 *        generated by CTR DRBG algorithm.
 *
 * @note This function assumes exclusive access to the CRACEN TRNG and CryptoMaster, and may
 *       not be used while any other component is using those peripherals.
 *
 * @param[out] p_buf Buffer into which to copy @p size generated bytes.
 * @param[in]  size  Number of bytes to copy.
 *
 * @retval 0          Success.
 * @retval -EINVAL    Invalid inputs.
 * @retval -ECANCELED Unexpected error.
 */
int nrfx_cracen_ctr_drbg_random_get(uint8_t * p_buf, size_t size);
#endif // NRF_CRACEN_HAS_CRYPTOMASTER

/**
 * @brief Function for filling a buffer with entropy from the CRACEN TRNG.
 *
 * When this function returns successfully, @p size random bytes have been written to @p p_buf.
 *
 * Up to @ref NRF_CRACEN_RNG_FIFO_SIZE bytes can be requested at once.
 * If more is requested the function will return @p -E2BIG without copying any data.
 *
 * The entropy generated by this function is NIST800-90B and AIS31 compliant, and can be used to
 * seed FIPS 140-2 compliant pseudo random number generators.
 *
 * @note This function is blocking. It will take around a couple of tenths of microseconds to
 *       complete depending on the amount of bytes requested.
 *       (~40 microseconds for an nRF54L15 for the maximum 64 bytes)
 *
 * @note This is a relatively power consuming operation.
 *
 * @warning This function assumes exclusive ownership of the CRACEN peripheral during execution.
 *
 * @param[out] p_buf Buffer into which to copy @p size bytes of entropy.
 * @param[in]  size  Number of bytes to copy.
 *
 * @retval 0       Success.
 * @retval -EINVAL Buffer or size is invalid.
 * @retval -E2BIG  The requested size is too big.
 */
int nrfx_cracen_entropy_get(uint8_t * p_buf, size_t size);

#ifndef NRFX_DECLARE_ONLY
#if NRF_CRACEN_HAS_CRYPTOMASTER
NRFX_STATIC_INLINE int nrfx_cracen_ctr_drbg_init(void)
{
    return nrfx_cracen_init();
}

NRFX_STATIC_INLINE void nrfx_cracen_ctr_drbg_uninit(void)
{
    nrfx_cracen_uninit();
}
#endif // NRF_CRACEN_HAS_CRYPTOMASTER
#endif // NRFX_DECLARE_ONLY
/** @} */

#ifdef __cplusplus
}
#endif

#endif /* NRFX_CRACEN_H */
